### ISSUE TITLE
Sidebar menu disappeared on Laravel Nova 3.4.0

### ISSUE THREAD

**Issue by newtongamajr** [saintsystems/nova-resource-group-menu#14]
Hi @anderly! I've tested some of the newest versions of Laravel Nova 3 and until version 3.3.2 the sidebar menu from nova-resource-group-menu is appearing correctly. On 3.4.0 it disappears, but if you access the URL directly, the resource menu is presented fine. Just the sidebar, is really with problems.

Thanks for your great package!

**Comment by anderly** [comment]
@newtongamajr thanks for reporting. I need to look at 3.x compatibility and will try to do that this week.

**Comment by marsdk** [comment]
Any news on 3.x compability ?

**Comment by anderly** [comment]
@newtongamajr @marsdk Works for me on a fresh install of Nova 3.10.0

Let me know if you're still seeing any issues.

**Comment by newtongamajr** [comment]
Sorry for not returning any information since the first report! Now its working fine since 3.6 The problem was solved!
