### ISSUE TITLE
Changes on Laravel Nova 3.19

### ISSUE THREAD

**Issue by newtongamajr** [saintsystems/nova-resource-group-menu#22]
Hi @anderly 

I was just updating my Laravel Nova project to 3.19.1 when I faced the problem above:

![Captura de tela 2021-01-09 152835](https://user-images.githubusercontent.com/8673343/104105807-90ea3080-528f-11eb-80fa-39eb73fd3f63.png)

After some analisys I observed that until 3.18 we'd the following scenario:

- ResourceGroupMenu extends Tool;
- Tool extends Card;
- Card extends Element;
- Element uses the trait Metable;

But on 3.19.1 (that I'm using now)

- ResourceGroupMenu extends Tool;
- Class Tool just use AuthorizedToSee, Makeble, ProxiesCanSeeToGate;

So many remaining methods that are used by ResourceGroupMenu are missing, like withMeta, width, and so on...

I suspect that this new change in Nova is very harmful, what do you think?

Best regards

**Comment by newtongamajr** [comment]
This change is mentioned here: https://github.com/laravel/nova/pull/1148

**Comment by eugenevdm** [comment]
Hi there, I'm getting:

> Call to undefined method SaintSystems\Nova\ResourceGroupMenu\ResourceGroupMenu::jsonSerialize()

which is making the plugin to stop working.

**Comment by ddkpdev** [comment]
I am experiencing the exact same issue as @newtongamajr.

**Comment by Ragash** [comment]
on laravel nova v 3.22 same problem as @eugenevdm 
jsonSerialize undefinded
