### ISSUE TITLE
Cannot read property 'group' of undefined

### ISSUE THREAD

**Issue by mhdHussein** [saintsystems/nova-resource-group-menu#4]
Hi there,
I did all the steps

the group shows up on the side menu but the page is empty
and in the chrome console i get the error :
TypeError: Cannot read property 'group' of undefined

**Comment by anderly** [comment]
This error indicates that your base `Resource` class doesn't have the `DisplaysInResourceGroupMenu` trait.

Please make sure you have added `use DisplaysInResourceGroupMenu;` to your base `Resource` class in the `app\Nova` folder.
