### ISSUE TITLE
Can not use route:cache

### ISSUE THREAD

**Issue by gldrenthe89** [saintsystems/nova-resource-group-menu#7]
The routes for nova-vendor/resource-group-menu uses closures wich is why i cannot use route:cache

**Comment by anderly** [comment]
Thanks for reporting this. I'll look at moving this to a controller so you can use route:cache.

**Comment by maartenpaauw** [comment]
@gldrenthe89 Thanks for fixing this! @anderly Could you please release this patch?

**Comment by anderly** [comment]
@maartenpaauw just released v0.1.0 with this fix.

**Comment by maartenpaauw** [comment]
Thank you!
